### ISSUE TITLE
Настроить непрерывную интеграцию 

### ISSUE THREAD

**Issue by AnastasiVokhmyanina28** [Students-of-the-city-of-Kostroma/trpo_automation#266]
# Срок сдачи: 21.04.20
### Epic:  #209
_Пояснения_: нет

**Comment by leshastern** [comment]
В процессе постижения такой вещи как непрерывная интеграция, я наткнулся на такой печальный факт: "When you want to use a Microsoft Azure Pipeline for your continuous integration with a QT project using a linux server, you'll need to create a self-managed linux VM and integrate it with QT and the azure pipeline system. This is because the Microsoft-hosted build servers do not natively support QT." (Если вы захотите настроить непрерывную интеграцию с QT проектом, вам придется арендовать виртуальную Linux-машину за свои деньги, и настраивать QT на ней. Все это потому, что сервера, расположенные у Miscosoft изначально не поддерживают QT.) Пруфы: [Раз](https://wiki.qt.io/QT_Azure_Pipeline_Integration) [Два](https://forum.qt.io/topic/97642/qt-integration-with-azure-pipeline/10)
Аренда VM стоит от $80/month

**Comment by YuriSilenok** [comment]
Решено: В запросах на слияние указывать DevOps в качестве проверяющего, который будет выполнять два тестирования, против ветки issue-* и 18-VTbo-2a после локального мержа
